# Generated by Django 5.1.6 on 2025-04-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_category_categoryid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="Description",
            field=models.CharField(max_length=500, verbose_name="description"),
        ),
    ]
