# Generated by Django 5.1.6 on 2026-10-05 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="Feedback",
            field=models.ManyToManyField(
                related_name="feedback_events",
                through="events.Feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="Registrations",
            field=models.ManyToManyField(
                related_name="registered_events",
                through="events.Registration",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="feedbackID"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=("UserID", "EventID"), name="unique_user_event_feedback"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("UserID", "EventID"), name="unique_user_event_registration"
            ),
        ),
    ]
